INSERT INTO questions (question_text, option_a, option_b) VALUES
('Would you rather', 'Always speak in rhymes', 'Always speak in riddles'),
('Would you rather', 'Have a pet dragon', 'Have a pet unicorn'),
('Would you rather', 'Be able to breathe underwater', 'Be able to fly'),
('Would you rather', 'Eat only desserts forever', 'Eat only vegetables forever'),
('Would you rather', 'Never have internet access again', 'Never watch TV again'),
('Would you rather', 'Be able to change your hair color at will', 'Be able to change your eye color at will'),
('Would you rather', 'Live in a world without gravity', 'Live in a world where it rains all the time'),
('Would you rather', 'Always have perfect hair', 'Always have perfect skin'),
('Would you rather', 'Be able to talk to plants', 'Be able to talk to animals'),
('Would you rather', 'Have super speed', 'Have super strength'),
('Would you rather', 'Be famous but constantly pursued by paparazzi', 'Be anonymous but live a peaceful life'),
('Would you rather', 'Be able to teleport anywhere instantly', 'Be able to time travel anywhere instantly'),
('Would you rather', 'Have unlimited chocolate', 'Have unlimited pizza'),
('Would you rather', 'Be invisible for one day', 'Be able to read minds for one day'),
('Would you rather', 'Always know everyone''s secrets', 'Always be able to keep a secret'),
('Would you rather', 'Live in a haunted house', 'Live in a castle in the clouds'),
('Would you rather', 'Be able to control fire', 'Be able to control water'),
('Would you rather', 'Have a rewind button for mistakes', 'Have a fast-forward button for boring moments'),
('Would you rather', 'Never have to sleep again', 'Never have to eat again'),
('Would you rather', 'Be a master of every musical instrument', 'Be a master of every language'),
('Would you rather', 'Experience zero gravity once', 'Experience deep sea diving once'),
('Would you rather', 'Always know the truth', 'Always be happy'),
('Would you rather', 'Live 200 years in the future', 'Live 200 years in the past'),
('Would you rather', 'Have a personal robot assistant', 'Have a personal spaceship'),
('Would you rather', 'Be able to see ghosts', 'Be able to see the future'),
('Would you rather', 'Have your dream job but no friends', 'Have a mediocre job but amazing friends'),
('Would you rather', 'Always have the latest tech', 'Always have the coolest clothes'),
('Would you rather', 'Be able to change the weather', 'Be able to control seasons'),
('Would you rather', 'Live in a floating city', 'Live underground in a futuristic bunker'),
('Would you rather', 'Never feel pain again', 'Never feel fear again'),
('Would you rather', 'Have a personal island', 'Have a personal skyscraper'),
('Would you rather', 'Be able to instantly learn any skill', 'Be able to instantly forget bad memories'),
('Would you rather', 'Always win every board game', 'Always win every video game'),
('Would you rather', 'Be able to control dreams', 'Be able to control memories'),
('Would you rather', 'Have a rewind button for the day', 'Have a pause button for life'),
('Would you rather', 'Be able to shrink to any size', 'Be able to grow to any size'),
('Would you rather', 'Have unlimited ice cream', 'Have unlimited coffee'),
('Would you rather', 'Live in a world made of candy', 'Live in a world made of toys'),
('Would you rather', 'Always know what people are thinking', 'Always be able to hide your thoughts'),
('Would you rather', 'Be a world-class chef', 'Be a world-class athlete'),
('Would you rather', 'Be able to talk to machines', 'Be able to talk to aliens'),
('Would you rather', 'Never have to pay for anything again', 'Be able to teleport anywhere for free'),
('Would you rather', 'Live in a fantasy world', 'Live in a sci-fi world'),
('Would you rather', 'Be able to live underwater', 'Be able to live in space'),
('Would you rather', 'Always have free tickets to concerts', 'Always have free access to movies'),
('Would you rather', 'Be able to predict the weather perfectly', 'Be able to predict stock market perfectly'),
('Would you rather', 'Have a supercomputer in your brain', 'Have a photographic memory'),
('Would you rather', 'Always have perfect luck', 'Always have perfect timing'),
('Would you rather', 'Live in a world with magic', 'Live in a world with advanced technology'),
('Would you rather', 'Be able to speak to all animals', 'Be able to speak all human languages'),
('Would you rather', 'Experience zero gravity every day', 'Experience 10x gravity every day'),
('Would you rather', 'Always have to whisper', 'Always have to shout'),
('Would you rather', 'Be able to see through walls', 'Be able to walk through walls'),
('Would you rather', 'Have a never-ending backpack', 'Have shoes that never wear out'),
('Would you rather', 'Be able to change your age at will', 'Be able to change your height at will'),
('Would you rather', 'Always smell everything strongly', 'Always taste everything strongly'),
('Would you rather', 'Have a personal theme song', 'Have a personal spotlight wherever you go'),
('Would you rather', 'Be able to clone yourself once', 'Be able to pause time for one hour'),
('Would you rather', 'Live in a giant treehouse', 'Live in an underwater dome'),
('Would you rather', 'Always know when it will rain', 'Always know when someone is lying'),
('Would you rather', 'Be a famous inventor', 'Be a famous explorer'),
('Would you rather', 'Have a magical wardrobe that gives you any outfit', 'Have a magical fridge that always has your favorite food'),
('Would you rather', 'Be able to change your voice to anyone', 'Be able to read anyone’s handwriting perfectly'),
('Would you rather', 'Live in a world where animals talk', 'Live in a world where robots feel emotions'),
('Would you rather', 'Have a personal teleportation pad', 'Have a personal flying car'),
('Would you rather', 'Always find the best deals while shopping', 'Always win every lottery you enter'),
('Would you rather', 'Have unlimited free books', 'Have unlimited free movies'),
('Would you rather', 'Be able to breathe fire', 'Be able to freeze things with your hands'),
('Would you rather', 'Live in a world with floating islands', 'Live in a world with giant underground cities'),
('Would you rather', 'Be a superhero with no powers', 'Be a normal person with super intelligence'),
('Would you rather', 'Always have perfect weather for your mood', 'Always know the mood of everyone around you'),
('Would you rather', 'Be able to instantly switch outfits', 'Be able to instantly switch hairstyles'),
('Would you rather', 'Have unlimited clean energy for your home', 'Have unlimited free transportation'),
('Would you rather', 'Be able to taste colors', 'Be able to see sounds'),
('Would you rather', 'Always have the best parking spot', 'Always have front row seats anywhere'),
('Would you rather', 'Be able to fly but only at night', 'Be able to teleport but only to familiar places'),
('Would you rather', 'Have a never-ending candy jar', 'Have a never-ending toy box'),
('Would you rather', 'Always have perfect memory of books', 'Always have perfect memory of movies'),
('Would you rather', 'Be able to speak to ghosts', 'Be able to see the future in dreams'),
('Would you rather', 'Live in a city floating in the sky', 'Live in a city underground with lights like stars'),
('Would you rather', 'Always have the perfect excuse', 'Always say the truth but no one believes you'),
('Would you rather', 'Be able to solve any puzzle instantly', 'Be able to invent anything instantly'),
('Would you rather', 'Have a garden that grows any plant instantly', 'Have a kitchen that cooks any dish instantly'),
('Would you rather', 'Live in a world without colors', 'Live in a world without music'),
('Would you rather', 'Be able to instantly learn dance moves', 'Be able to instantly learn any instrument'),
('Would you rather', 'Have an endless supply of shoes', 'Have an endless supply of hats'),
('Would you rather', 'Be able to talk to computers', 'Be able to talk to cars'),
('Would you rather', 'Live in a world where everyone is honest', 'Live in a world where everyone is polite'),
('Would you rather', 'Have super hearing', 'Have super vision'),
('Would you rather', 'Be a famous artist but broke', 'Be rich but never creative'),
('Would you rather', 'Always find your keys instantly', 'Always find your wallet instantly'),
('Would you rather', 'Be able to paint anything perfectly', 'Be able to sculpt anything perfectly'),
('Would you rather', 'Live in a constant summer', 'Live in a constant winter'),
('Would you rather', 'Be able to taste music', 'Be able to hear colors'),
('Would you rather', 'Have a magic pen that writes anything', 'Have a magic notebook that stores anything you want'),
('Would you rather', 'Be able to change your height at will', 'Be able to change your weight at will'),
('Would you rather', 'Always be fashionable', 'Always be witty'),
('Would you rather', 'Have your favorite food appear instantly', 'Have unlimited favorite drinks appear instantly'),
('Would you rather', 'Be able to remember everyone’s name', 'Be able to remember everyone’s birthday'),
('Would you rather', 'Always win at trivia', 'Always win at physical games'),
('Would you rather', 'Have a personal island with luxury', 'Have a personal spaceship with exploration'),
('Would you rather', 'Be able to speak to your past self', 'Be able to speak to your future self'),
('Would you rather', 'Always know the ending of a story', 'Always know the beginning of a story'),
('Would you rather', 'Be able to instantly write books', 'Be able to instantly compose music'),
('Would you rather', 'Live in a world with magic portals', 'Live in a world with teleporting elevators'),
('Would you rather', 'Have a secret lair', 'Have a hidden treasure'),
('Would you rather', 'Be able to taste emotions', 'Be able to smell emotions'),
('Would you rather', 'Always have perfect timing', 'Always have perfect coordination'),
('Would you rather', 'Be able to mimic any voice', 'Be able to mimic any movement'),
('Would you rather', 'Have unlimited battery life for all devices', 'Have unlimited storage for all devices'),
('Would you rather', 'Be a master chef in every cuisine', 'Be a master at every sport'),
('Would you rather', 'Live in a house that moves with you', 'Live in a car that can fly'),
('Would you rather', 'Be able to turn invisible at will', 'Be able to fly at will'),
('Would you rather', 'Have a magic carpet', 'Have a magic submarine'),
('Would you rather', 'Always find lost items', 'Always remember important dates'),
('Would you rather', 'Be able to talk to any animal', 'Be able to talk to any plant'),
('Would you rather', 'Be able to survive in space', 'Be able to survive underwater'),
('Would you rather', 'Have perfect handwriting', 'Have perfect drawing skills'),
('Would you rather', 'Be able to instantly memorize everything', 'Be able to instantly understand anything'),
('Would you rather', 'Have a tiny robot helper', 'Have a huge robot protector'),
('Would you rather', 'Live in a candy-themed world', 'Live in a toy-themed world'),
('Would you rather', 'Be able to control luck', 'Be able to control probability'),
('Would you rather', 'Always have a perfect selfie', 'Always have a perfect group photo'),
('Would you rather', 'Be able to travel through books', 'Be able to travel through movies'),
('Would you rather', 'Always know the best route to travel', 'Always find the fastest checkout line'),
('Would you rather', 'Have endless bubble gum', 'Have endless chocolate'),
('Would you rather', 'Be able to swim in lava safely', 'Be able to fly in storms safely'),
('Would you rather', 'Always be in a good mood', 'Always have everyone like you'),
('Would you rather', 'Be able to manipulate shadows', 'Be able to manipulate light'),
('Would you rather', 'Have a magical camera', 'Have a magical journal'),
('Would you rather', 'Live in a world made of ice cream', 'Live in a world made of chocolate'),
('Would you rather', 'Have an endless library', 'Have an endless music collection'),
('Would you rather', 'Always have perfect balance', 'Always have perfect aim'),
('Would you rather', 'Be able to control gravity', 'Be able to control magnetism'),
('Would you rather', 'Have a teleporting house', 'Have a transforming car'),
('Would you rather', 'Always know who is lying', 'Always know who is telling the truth'),
('Would you rather', 'Be able to create portals', 'Be able to create force fields'),
('Would you rather', 'Be able to morph into any animal', 'Be able to morph into any person'),
('Would you rather', 'Have unlimited creativity', 'Have unlimited intelligence'),
('Would you rather', 'Be able to talk to inanimate objects', 'Be able to talk to elements like fire and water'),
('Would you rather', 'Always find the perfect gift', 'Always find the perfect advice'),
('Would you rather', 'Have a floating city apartment', 'Have an underwater city apartment'),
('Would you rather', 'Be able to control your dreams', 'Be able to control your memories'),
('Would you rather', 'Always have a backup plan', 'Always have a perfect plan'),
('Would you rather', 'Be able to walk through walls', 'Be able to fly through walls'),
('Would you rather', 'Have perfect taste in food', 'Have perfect taste in music'),
('Would you rather', 'Be able to shrink at will', 'Be able to grow at will'),
('Would you rather', 'Be able to turn invisible in shadows', 'Be able to fly in sunlight'),
('Would you rather', 'Always be first in line', 'Always have a VIP pass everywhere'),
('Would you rather', 'Be able to teleport into books', 'Be able to teleport into movies'),
('Would you rather', 'Be able to instantly repair anything', 'Be able to instantly upgrade anything'),
('Would you rather', 'Always have a perfect view', 'Always have the perfect company'),
('Would you rather', 'Be able to talk to all pets', 'Be able to talk to all wild animals'),
('Would you rather', 'Always have perfect sleep', 'Always have perfect energy'),
('Would you rather', 'Be able to speak all human languages fluently', 'Be able to speak all alien languages fluently'),
('Would you rather', 'Be able to live without food', 'Be able to live without sleep'),
('Would you rather', 'Have endless summer', 'Have endless winter'),
('Would you rather', 'Have a robot butler', 'Have a robot chef'),
('Would you rather', 'Be able to fly like a bird', 'Be able to swim like a dolphin'),
('Would you rather', 'Be able to talk to your past self', 'Be able to talk to your future self'),
('Would you rather', 'Always know the weather perfectly', 'Always know the traffic perfectly'),
('Would you rather', 'Be able to travel through dreams', 'Be able to travel through memories'),
('Would you rather', 'Have a magical pen that draws anything', 'Have a magical camera that captures anything'),
('Would you rather', 'Live in a castle in the sky', 'Live in a palace underwater'),
('Would you rather', 'Be able to read any book instantly', 'Be able to watch any movie instantly'),
('Would you rather', 'Have super speed but low endurance', 'Have super strength but low agility'),
('Would you rather', 'Always be able to find a parking spot', 'Always be able to find a charging station'),
('Would you rather', 'Have a cloud car', 'Have a submarine car'),
('Would you rather', 'Be able to live in any historical era', 'Be able to live in any future era'),
('Would you rather', 'Always know the perfect thing to say', 'Always know the perfect thing to do'),
('Would you rather', 'Be able to speak to all animals', 'Be able to speak to all humans perfectly'),
('Would you rather', 'Have a secret teleportation device', 'Have a secret invisibility device'),
('Would you rather', 'Be able to predict the stock market', 'Be able to predict natural events'),
('Would you rather', 'Always have perfect vision', 'Always have perfect hearing'),
('Would you rather', 'Have a magical backpack', 'Have magical shoes'),
('Would you rather', 'Be able to control fire and ice', 'Be able to control earth and air'),
('Would you rather', 'Always find lost items instantly', 'Always remember important moments instantly'),
('Would you rather', 'Be able to talk to your future self', 'Be able to talk to your past self'),
('Would you rather', 'Live in a world made of candy', 'Live in a world made of toys'),
('Would you rather', 'Have the ability to shape-shift', 'Have the ability to clone yourself'),
('Would you rather', 'Always have the best food', 'Always have the best drinks'),
('Would you rather', 'Be able to walk on water', 'Be able to fly through clouds'),
('Would you rather', 'Have a magic garden', 'Have a magic library'),
('Would you rather', 'Be able to instantly learn anything', 'Be able to instantly forget any regret'),
('Would you rather', 'Always know the right answer', 'Always know the perfect timing'),
('Would you rather', 'Have endless chocolate', 'Have endless ice cream'),
('Would you rather', 'Be able to talk to machines', 'Be able to talk to nature'),
('Would you rather', 'Live in a city with floating cars', 'Live in a city with teleportation stations'),
('Would you rather', 'Always have a perfect smile', 'Always have a perfect style'),
('Would you rather', 'Be able to control time for 10 minutes', 'Be able to control space for 10 minutes'),
('Would you rather', 'Always have the perfect idea', 'Always have the perfect friend'),
('Would you rather', 'Be able to relive your happiest day', 'Be able to erase your worst day'),
('Would you rather', 'Be able to jump anywhere instantly', 'Be able to move objects with your mind'),
('Would you rather', 'Live on a floating island', 'Live in a giant treehouse'),
('Would you rather', 'Have a magic potion for any skill', 'Have a magic potion for any knowledge'),
('Would you rather', 'Always be able to speak your mind', 'Always be able to read minds'),
('Would you rather', 'Be able to change the color of anything', 'Be able to change the shape of anything'),
('Would you rather', 'Have a personal AI assistant', 'Have a personal magical creature'),
('Would you rather', 'Be able to create portals anywhere', 'Be able to create shields anywhere'),
('Would you rather', 'Always have perfect coordination', 'Always have perfect reflexes'),
('Would you rather', 'Be able to talk to insects', 'Be able to talk to birds'),
('Would you rather', 'Live in a candy world', 'Live in a chocolate world'),
('Would you rather', 'Always have a perfect song playing', 'Always have perfect weather'),
('Would you rather', 'Be able to fly like a superhero', 'Be able to swim like a mermaid'),
('Would you rather', 'Have a magical wardrobe', 'Have a magical fridge'),
('Would you rather', 'Be able to teleport anywhere once a day', 'Be able to time travel once a day'),
('Would you rather', 'Be able to instantly heal yourself', 'Be able to instantly heal others'),
('Would you rather', 'Always have unlimited battery', 'Always have unlimited internet'),
('Would you rather', 'Be able to communicate with aliens', 'Be able to communicate with animals'),
('Would you rather', 'Have a personal flying car', 'Have a personal submarine'),
('Would you rather', 'Be able to transform into any object', 'Be able to transform into any person'),
('Would you rather', 'Live in a world with magic', 'Live in a world with advanced technology'),
('Would you rather', 'Be able to talk to trees', 'Be able to talk to rocks'),
('Would you rather', 'Have a personal island with anything you want', 'Have a personal palace with anything you want'),
('Would you rather', 'Be able to control dreams', 'Be able to control memories'),
('Would you rather', 'Always know the perfect solution', 'Always know the perfect question'),
('Would you rather', 'Be able to speak to all humans', 'Be able to speak to all animals'),
('Would you rather', 'Always have perfect luck', 'Always have perfect timing'),
('Would you rather', 'Be able to control gravity', 'Be able to control magnetism'),
('Would you rather', 'Be able to create illusions', 'Be able to see through illusions'),
('Would you rather', 'Have endless candy', 'Have endless toys'),
('Would you rather', 'Live in a castle in the clouds', 'Live in a mansion under the sea'),
('Would you rather', 'Always have perfect energy', 'Always have perfect sleep'),
('Would you rather', 'Be able to teleport instantly', 'Be able to fly instantly'),
('Would you rather', 'Have a personal robot chef', 'Have a personal robot bodyguard'),
('Would you rather', 'Be able to read any book instantly', 'Be able to watch any movie instantly'),
('Would you rather', 'Always have perfect vision', 'Always have perfect hearing'),
('Would you rather', 'Be able to talk to machines', 'Be able to talk to nature'),
('Would you rather', 'Be able to shape-shift at will', 'Be able to clone yourself at will'),
('Would you rather', 'Always have perfect balance', 'Always have perfect aim'),
('Would you rather', 'Be able to control fire', 'Be able to control water'),
('Would you rather', 'Be able to fly through clouds', 'Be able to walk on water'),
('Would you rather', 'Have a magical library', 'Have a magical garden');
