INSERT INTO questions (question_text, option_a, option_b) VALUES
('Would you rather', 'Live a life of complete honesty but constantly hurt those you love', 'Lie occasionally but keep peace with everyone'),
('Would you rather', 'Have infinite wealth but no meaningful relationships', 'Have close relationships but always struggle financially'),
('Would you rather', 'Be able to control time but lose one year of your life each time', 'Live normally but never manipulate time'),
('Would you rather', 'Experience extreme happiness for one week but sadness for a year', 'Live a life of moderate happiness and moderate sadness'),
('Would you rather', 'Know everything about everyone else but lose your privacy', 'Keep your privacy but never know anyone’s true intentions'),
('Would you rather', 'Be able to read all minds but feel their emotions intensely', 'Never read minds but feel emotions normally'),
('Would you rather', 'Live in a world without conflict but also without love', 'Live in a world with love and conflict intertwined'),
('Would you rather', 'Save one loved one at the cost of ten strangers', 'Save ten strangers at the cost of one loved one'),
('Would you rather', 'Be remembered in history but forgotten by your family', 'Be loved by your family but forgotten historically'),
('Would you rather', 'Be able to speak every language but never express emotion', 'Express emotion fully but speak only one language'),
('Would you rather', 'Have a perfect career but no personal life', 'Have a perfect personal life but a mediocre career'),
('Would you rather', 'Live forever but feel lonely eternally', 'Live a normal lifespan surrounded by loved ones'),
('Would you rather', 'Be the smartest person in the world but socially isolated', 'Be socially popular but intellectually average'),
('Would you rather', 'Change one event in your past but forget who you are', 'Keep your identity intact but never change your past'),
('Would you rather', 'Be able to heal others but feel their pain', 'Keep yourself safe but let others suffer'),
('Would you rather', 'Experience all the joy of life but none of the pain', 'Experience all the pain of life but none of the joy'),
('Would you rather', 'Know the exact moment you will die', 'Never know when you will die but live unpredictably'),
('Would you rather', 'Be able to relive moments but feel them half as strongly', 'Experience life fully but never relive any moment'),
('Would you rather', 'Have infinite creativity but no execution skills', 'Have execution skills but no creativity'),
('Would you rather', 'Always find the perfect solution too late', 'Act quickly but always imperfectly'),
('Would you rather', 'Live a short thrilling life', 'Live a long boring life'),
('Would you rather', 'Be loved universally but never truly happy yourself', 'Be happy yourself but disliked by most people'),
('Would you rather', 'Remember everything perfectly but never forget painful memories', 'Forget painful memories but also forget some happy ones'),
('Would you rather', 'Experience ultimate happiness for one week', 'Live a moderate happiness for a lifetime'),
('Would you rather', 'Have every wish granted but regret each one', 'Live with limitations but no regrets'),
('Would you rather', 'Be able to forgive anyone but never be forgiven', 'Be forgiven easily but never forgive'),
('Would you rather', 'Travel anywhere instantly but never take anyone with you', 'Travel slowly but with loved ones'),
('Would you rather', 'Lose the ability to lie', 'Lose the ability to tell the truth'),
('Would you rather', 'Live without fear but also without excitement', 'Feel fear often but live thrilling experiences'),
('Would you rather', 'Have unlimited money but feel unfulfilled', 'Have little money but feel deeply fulfilled'),
('Would you rather', 'Be able to see everyone’s true emotions but feel none yourself', 'Feel your emotions fully but never know others’ emotions'),
('Would you rather', 'Change the past but alter your personality', 'Keep your personality intact but never change the past'),
('Would you rather', 'Be brilliant in your career but never form friendships', 'Have strong friendships but mediocre career'),
('Would you rather', 'Experience extreme happiness and sadness alternately', 'Live life with steady moderate emotions'),
('Would you rather', 'Be famous and constantly criticized', 'Be unknown but loved by those who know you'),
('Would you rather', 'Live a perfect life in a simulation', 'Live a flawed life in reality'),
('Would you rather', 'Have infinite knowledge but no wisdom', 'Have wisdom but limited knowledge'),
('Would you rather', 'Be able to stop time but feel extreme fatigue afterward', 'Live normally without controlling time'),
('Would you rather', 'Live in total isolation with comfort', 'Live in chaos with community'),
('Would you rather', 'Be able to speak to animals but lose human speech', 'Keep human speech but never understand animals'),
('Would you rather', 'Have a perfect life but never experience love', 'Experience love but with challenges and hardships'),
('Would you rather', 'Always know the right choice but never act on it', 'Act freely but often make wrong choices'),
('Would you rather', 'Live with no regrets but never take risks', 'Take risks and make mistakes but have memories to cherish'),
('Would you rather', 'Remember every detail of your life but never form new memories', 'Forget old memories gradually but fully enjoy new experiences'),
('Would you rather', 'Be able to manipulate time but age faster', 'Live normally but experience time at regular pace'),
('Would you rather', 'Be extremely talented but unrecognized', 'Be average but celebrated by everyone'),
('Would you rather', 'Have the power to fix mistakes but lose a year of life each time', 'Live without regrets but never fix mistakes'),
('Would you rather', 'Experience every joy and pain of everyone you meet', 'Live your own life isolated from others’ emotions'),
('Would you rather', 'Be able to erase your worst memories but forget some of your happiest moments', 'Keep all memories, good and bad, forever'),
('Would you rather', 'Be able to change your appearance at will but never feel comfortable in your own body', 'Stay in your natural body but be instantly recognized everywhere'),
('Would you rather', 'Be able to stop time for 10 seconds per day', 'Be able to rewind 10 seconds of your life once per day'),
('Would you rather', 'Be able to read minds but they can also read yours', 'Keep your mind private but never know what anyone else thinks'),
('Would you rather', 'Have everything you desire now but regret it later', 'Wait for things slowly and avoid regret'),
('Would you rather', 'Be able to save lives but suffer severe consequences each time', 'Live safely but never help anyone'),
('Would you rather', 'Be able to speak any language but never understand emotion', 'Understand emotion perfectly but speak only your native language'),
('Would you rather', 'Be able to relive your happiest moment but forget another important one', 'Keep all memories intact but never relive your happiest moment'),
('Would you rather', 'Experience the happiest day of your life repeatedly but nothing else', 'Live a normal life with highs and lows but never repeat the happiest day'),
('Would you rather', 'Have unlimited pizza but only plain cheese', 'Have normal pizza but unlimited toppings'),
('Would you rather', 'Be able to forgive others instantly but never be forgiven', 'Be forgiven easily but take a long time to forgive'),
('Would you rather', 'Be able to speak fluently to animals but lose the ability to speak humans', 'Keep human speech but never understand animals'),
('Would you rather', 'Live forever in a comfortable bubble but never grow', 'Live a normal life but constantly face challenges'),
('Would you rather', 'Have perfect memory but never forget any painful moment', 'Forget painful memories but risk losing joyful ones'),
('Would you rather', 'Be able to change the past but alter your personality', 'Keep your personality intact but never change the past'),
('Would you rather', 'Be able to stop time but lose one year of your life each time', 'Live normally without manipulating time'),
('Would you rather', 'Be able to manipulate reality but lose one sense permanently', 'Keep all senses intact but never manipulate reality'),
('Would you rather', 'Experience all emotions at once intensely', 'Experience emotions slowly and mildly'),
('Would you rather', 'Live in a world without suffering but also without love', 'Live in a world with love and suffering intertwined'),
('Would you rather', 'Be brilliant but socially awkward', 'Be socially charming but average in intelligence'),
('Would you rather', 'Be famous but constantly criticized', 'Be unknown but completely free'),
('Would you rather', 'Always be right but never convince anyone', 'Be wrong often but always persuade others');
