INSERT INTO questions (question_text, option_a, option_b) VALUES
('Would you rather', 'Be able to read every book instantly but forget everything after a week', 'Only read one book at a time but remember it forever'),
('Would you rather', 'Always have to tell the truth', 'Always have to lie'),
('Would you rather', 'Be able to time travel but never control where you go', 'Stay in the present forever'),
('Would you rather', 'Have unlimited wealth but never love', 'Have true love but struggle financially'),
('Would you rather', 'Be famous and constantly judged', 'Be unknown and completely free'),
('Would you rather', 'Lose your sense of taste forever', 'Lose your sense of smell forever'),
('Would you rather', 'Always know what people think about you', 'Never know what people think about you'),
('Would you rather', 'Live in a world without music', 'Live in a world without movies'),
('Would you rather', 'Be able to stop time but age faster', 'Live normally without controlling time'),
('Would you rather', 'Be able to teleport anywhere but only once per day', 'Be able to fly but only at walking speed'),
('Would you rather', 'Always win arguments but never be liked', 'Be loved by everyone but always lose arguments'),
('Would you rather', 'Have perfect memory but no imagination', 'Have perfect imagination but forgetful memory'),
('Would you rather', 'Be able to speak every language but never express emotions', 'Express emotions fully but speak only one language'),
('Would you rather', 'Be able to control animals but never communicate with humans', 'Communicate perfectly with humans but never animals'),
('Would you rather', 'Have a rewind button for life but lose a year each time', 'Have a pause button for life but feel every second'),
('Would you rather', 'Live 1000 years alone', 'Live 50 years surrounded by loved ones'),
('Would you rather', 'Experience extreme happiness for a day but sadness for a year', 'Live with moderate happiness and sadness for life'),
('Would you rather', 'Be able to manipulate luck', 'Be able to manipulate time slightly'),
('Would you rather', 'Be famous for a terrible reason', 'Be completely unknown for a great reason'),
('Would you rather', 'Have a photographic memory but feel no emotions', 'Feel every emotion strongly but forget everything quickly'),
('Would you rather', 'Always find lost items', 'Always remember important dates'),
('Would you rather', 'Be able to see the future but never change it', 'Change the past but forget what you learned'),
('Would you rather', 'Live without technology', 'Live without nature'),
('Would you rather', 'Be able to talk to your past self', 'Be able to talk to your future self'),
('Would you rather', 'Always be too hot', 'Always be too cold'),
('Would you rather', 'Live in total chaos but free', 'Live in complete order but controlled'),
('Would you rather', 'Be able to fly but feel tired quickly', 'Run super fast but never jump high'),
('Would you rather', 'Have unlimited food but gain weight uncontrollably', 'Eat normally but never gain weight'),
('Would you rather', 'Never be able to lie', 'Never be able to tell the truth'),
('Would you rather', 'Live without music forever', 'Live without movies forever'),
('Would you rather', 'Always know the truth but feel terrible', 'Be blissfully ignorant but happy'),
('Would you rather', 'Be able to read minds but feel their emotions', 'Never read minds but feel only your own emotions'),
('Would you rather', 'Have the ability to see all possibilities but choose none', 'Have no insight but always make quick decisions'),
('Would you rather', 'Be able to speak to machines', 'Be able to speak to animals'),
('Would you rather', 'Have unlimited energy but no sleep', 'Sleep perfectly but always feel tired'),
('Would you rather', 'Be able to control the weather but only locally', 'Be able to control your luck globally'),
('Would you rather', 'Be a genius but socially awkward', 'Be average intelligence but socially loved'),
('Would you rather', 'Live forever but lonely', 'Live a normal lifespan surrounded by friends'),
('Would you rather', 'Have every wish granted but regret each one', 'Live with limitations but no regrets'),
('Would you rather', 'Be able to forgive anyone but never be forgiven', 'Be forgiven easily but never forgive'),
('Would you rather', 'Travel anywhere instantly but always alone', 'Travel slowly but with loved ones'),
('Would you rather', 'Lose the ability to lie', 'Lose the ability to tell the truth'),
('Would you rather', 'Live without fear but also without excitement', 'Feel fear often but live thrilling experiences'),
('Would you rather', 'Have unlimited money but feel unfulfilled', 'Have little money but feel deeply fulfilled'),
('Would you rather', 'Be able to see everyone''s true emotions but feel none yourself', 'Feel your emotions fully but never know others'' emotions'),
('Would you rather', 'Change the past but alter your personality', 'Keep your personality intact but never change the past'),
('Would you rather', 'Be brilliant in your career but never form friendships', 'Have strong friendships but mediocre career'),
('Would you rather', 'Experience extreme happiness and sadness alternately', 'Live life with steady moderate emotions'),
('Would you rather', 'Be famous and constantly criticized', 'Be unknown but loved by those who know you'),
('Would you rather', 'Live a perfect life in a simulation', 'Live a flawed life in reality'),
('Would you rather', 'Have infinite knowledge but no wisdom', 'Have wisdom but limited knowledge'),
('Would you rather', 'Be able to stop time but feel extreme fatigue afterward', 'Live normally without controlling time'),
('Would you rather', 'Live in total isolation with comfort', 'Live in chaos with community'),
('Would you rather', 'Be able to speak to animals but lose human speech', 'Keep human speech but never understand animals'),
('Would you rather', 'Have a perfect life but never experience love', 'Experience love but with challenges and hardships'),
('Would you rather', 'Always know the right choice but never act on it', 'Act freely but often make wrong choices'),
('Would you rather', 'Live with no regrets but never take risks', 'Take risks and make mistakes but have memories to cherish'),
('Would you rather', 'Remember every detail of your life but never form new memories', 'Forget old memories gradually but fully enjoy new experiences'),
('Would you rather', 'Be able to manipulate time but age faster', 'Live normally but experience time at regular pace'),
('Would you rather', 'Be extremely talented but unrecognized', 'Be average but celebrated by everyone'),
('Would you rather', 'Have the power to fix mistakes but lose a year of life each time', 'Live without regrets but never fix mistakes'),
('Would you rather', 'Experience every joy and pain of everyone you meet', 'Live your own life isolated from others’ emotions'),
('Would you rather', 'Be able to erase your worst memories but forget some of your happiest moments', 'Keep all memories, good and bad, forever'),
('Would you rather', 'Be able to change your appearance at will but never feel comfortable in your own body', 'Stay in your natural body but be instantly recognized everywhere'),
('Would you rather', 'Be able to stop time for 10 seconds per day', 'Be able to rewind 10 seconds of your life once per day'),
('Would you rather', 'Be able to read minds but they can also read yours', 'Keep your mind private but never know what anyone else thinks'),
('Would you rather', 'Have everything you desire now but regret it later', 'Wait for things slowly and avoid regret'),
('Would you rather', 'Be able to save lives but suffer severe consequences each time', 'Live safely but never help anyone'),
('Would you rather', 'Be able to speak any language but never understand emotion', 'Understand emotion perfectly but speak only your native language'),
('Would you rather', 'Be able to relive your happiest moment but forget another important one', 'Keep all memories intact but never relive your happiest moment'),
('Would you rather', 'Experience the happiest day of your life repeatedly but nothing else', 'Live a normal life with highs and lows but never repeat the happiest day'),
('Would you rather', 'Have unlimited pizza but only plain cheese', 'Have normal pizza but unlimited toppings'),
('Would you rather', 'Be able to forgive others instantly but never be forgiven', 'Be forgiven easily but take a long time to forgive'),
('Would you rather', 'Be able to speak fluently to animals but lose the ability to speak humans', 'Keep human speech but never understand animals'),
('Would you rather', 'Live forever in a comfortable bubble but never grow', 'Live a normal life but constantly face challenges'),
('Would you rather', 'Have perfect memory but never forget any painful moment', 'Forget painful memories but risk losing joyful ones'),
('Would you rather', 'Be able to change the past but alter your personality', 'Keep your personality intact but never change the past'),
('Would you rather', 'Be able to stop time but lose one year of your life each time', 'Live normally without manipulating time'),
('Would you rather', 'Be able to manipulate reality but lose one sense permanently', 'Keep all senses intact but never manipulate reality'),
('Would you rather', 'Experience all emotions at once intensely', 'Experience emotions slowly and mildly'),
('Would you rather', 'Live in a world without suffering but also without love', 'Live in a world with love and suffering intertwined'),
('Would you rather', 'Be brilliant but socially awkward', 'Be socially charming but average in intelligence'),
('Would you rather', 'Be famous but constantly criticized', 'Be unknown but completely free'),
('Would you rather', 'Always be right but never convince anyone', 'Be wrong often but always persuade others');
