INSERT INTO questions (question_text, option_a, option_b) VALUES
('Would you rather', 'Eat for free but never eat your favorite food', 'Eat for free but you can only eat your favorite food'),
('Would you rather', 'Travel anywhere for free but never stay in hotels', 'Travel anywhere but pay for everything and stay in luxury hotels'),
('Would you rather', 'Have unlimited energy but no sleep', 'Sleep perfectly but always feel a little tired'),
('Would you rather', 'Be famous but constantly criticized', 'Be unknown but loved by everyone who knows you'),
('Would you rather', 'Have a job you love but low pay', 'Have a high-paying job you hate'),
('Would you rather', 'Always know the exact time but lose track of days', 'Never know the exact time but always know the day'),
('Would you rather', 'Have unlimited books but no internet', 'Have unlimited internet but never read books'),
('Would you rather', 'Be able to see the future but not change it', 'Change the past but forget everything you learned'),
('Would you rather', 'Always have free Wi-Fi but slow internet', 'Pay for fast internet everywhere'),
('Would you rather', 'Live in a world without music but have movies', 'Live in a world without movies but have music'),
('Would you rather', 'Be able to eat anything without gaining weight but feel hungry constantly', 'Eat normally but never gain weight or feel hungry'),
('Would you rather', 'Have your dream house but no neighbors', 'Live in a small apartment in a lively city'),
('Would you rather', 'Always be too hot but never cold', 'Always be too cold but never hot'),
('Would you rather', 'Speak every language but never be understood emotionally', 'Speak only one language but communicate perfectly'),
('Would you rather', 'Have free rides everywhere but slow travel', 'Travel fast everywhere but pay for every ride'),
('Would you rather', 'Be able to stop time for 10 seconds per day', 'Be able to rewind 10 seconds of your life once per day'),
('Would you rather', 'Always get everything you want but lose your privacy', 'Keep your privacy but never get everything you want'),
('Would you rather', 'Have unlimited pizza but only plain cheese', 'Have normal pizza but unlimited toppings'),
('Would you rather', 'Always have to sing instead of talk', 'Always have to dance instead of walk'),
('Would you rather', 'Be able to read minds but feel every emotion intensely', 'Never read minds but feel emotions normally');
