INSERT INTO questions (question_text, option_a, option_b) VALUES
('Would you rather', 'Never use a smartphone again', 'Never use a computer again'),
('Would you rather', 'Always be 20 minutes late', 'Always be 20 minutes early'),
('Would you rather', 'Live without music', 'Live without movies'),
('Would you rather', 'Have unlimited international first-class flights', 'Never have to pay for food at restaurants'),
('Would you rather', 'Be able to speak every language', 'Be able to speak to animals'),
('Would you rather', 'Lose all your photos', 'Lose all your messages'),
('Would you rather', 'Never be stuck in traffic again', 'Never get another cold'),
('Would you rather', 'Have perfect memory', 'Be able to forget anything instantly'),
('Would you rather', 'Live on a beach', 'Live in the mountains'),
('Would you rather', 'Have 1 million dollars now', 'Have 10k per month forever'),
('Would you rather', 'Always feel slightly too hot', 'Always feel slightly too cold'),
('Would you rather', 'Be invisible at will', 'Fly at walking speed'),
('Would you rather', 'Have free Netflix and Spotify forever', 'Have free coffee forever'),
('Would you rather', 'Work 4 days a week for less money', 'Work 6 days a week for more money'),
('Would you rather', 'Have no taste buds', 'Have no sense of smell'),
('Would you rather', 'Be able to teleport but only to places you’ve been', 'Time travel but only backward'),
('Would you rather', 'Win every game you play', 'Never lose an argument'),
('Would you rather', 'Eat only spicy food forever', 'Eat only bland food forever'),
('Would you rather', 'Have a rewind button for your life', 'Have a pause button'),
('Would you rather', 'Always know when someone lies', 'Always get away with lying');
